Repository GSG-G13/autocomplete-Abeer-Mohammed, pull requests merged in 2023-03, with the labels that each got.

#2 add file-structure#1
  public/index.html
  public/js/dom.js
  public/js/xhr.js
  public/style.css
  src/router.js
  src/server.js
Labels: waiting-review, done

#7 html file
  public/index.html
Labels: done

#8 html edit
  public/index.html
Labels: waiting-review

#9 add css file
  public/logo.png
  public/style.css
Labels: done

#13 add server file
  src/server.js
Labels: done

#14 add router file
  src/router.js
Labels: done

#15 add handler
  src/handler/handlerPublic.js
Labels: done

#17 add file data Relates#16
  src/values.json
Labels: waiting-review

#19 add export modules Relates#18
  src/handler/handlerPublic.js
Labels: done

#20 edit module
  src/handler/handlerPublic.js
  src/router.js
Labels: done

#23 add request Relates#22
  public/favicon.ico
  public/js/xhr.js
  src/router.js
Labels: done

#25 handlepublic function Relates#24
  src/handler/handlerPublic.js
  src/router.js
Labels: done

#27 handle fun Relates#26
  public/js/dom.js
Labels: done

#35 add responsive
  public/style.css
Labels: waiting-review

#34 empty ul and input Relates#32
  public/js/dom.js
  src/handler/handlerPublic.js
  src/router.js
Labels: done

#37 add file package Relates#36
  package.json
Labels: done

#38 Update README.md
  README.md
Labels: waiting-review
